### ISSUE TITLE
Aggiungere Travis CI

### ISSUE THREAD

**Issue by matteocontrini** [matteocontrini/comuni-json#12]
Ad ogni commit Travis dovrebbe:

- Eseguire `npm run validate`
- Fare una build della cartella `data`, per escludere altri problemi nei file di origine
- Confrontare la build generata con il file `comuni.json`, in modo da essere certi che la versione "compilata" rifletta i dati nella cartella `data`

**Comment by andreafalzetti** [comment]
Ciao! Sarebbe carino aggiungere Travis e anche pubblicare il modulo su npm, cosa ne pensi?

Se vuoi, posso darti una mano con una PR. Let me know

**Comment by matteocontrini** [comment]
Ciao, per quanto riguarda Travis come vedi è in programma da molto tempo. Sarebbe utile per automatizzare la validazione dei dati, giusto come secondo controllo, che comunque eseguo manualmente in locale (quando mi ricordo 😬).

Per npm, il file package.json esiste in realtà soltanto per poter gestire le dipendenze per far funzionare lo script di validazione e "build" (ci sono anche altre `devDependencies` ma non servono più, le ho dimenticate).

Credo si potrebbe in effetti pubblicare su npm adattando un po' il package.json (idealmente escludendo la cartella `data` e altre cose inutili dal pacchetto). Pensi possa essere utile, però? Pensavo che l'uso principale di questi dati fosse per importarli in qualche database, piuttosto che caricarli direttamente in memoria.

Al di là di tutto, detto sinceramente non ho molto tempo da dedicare a queste due cose (riesco a malapena a tenere aggiornati i dati), quindi accetto contributi eventualmente :)
