### ISSUE TITLE
chiave "sigla"

### ISSUE THREAD

**Issue by 3zone** [matteocontrini/comuni-json#13]
1) La chiave "sigla" IMHO era piu' sensato inserirla all'interno della chiave "provincia" (assieme alle alte 2: "codice" e "nome").

OPPURE

2) la chiave "sigla" era piu sensato chiamarla "sigla-provincia", ma a questo punto risulta piu' sensato quanto detto al primo punto.

**Comment by matteocontrini** [comment]
Ciao, la sigla non è legata alla provincia ma alla provincia o alla città metropolitana. È fuori per questo motivo. Oltre al fatto che la sigla non si chiama "sigla della provincia" ma "sigla automobilistica", dal 1927 :)
