### ISSUE TITLE
Aggiungere mail pec

### ISSUE THREAD

**Issue by reuseman** [matteocontrini/comuni-json#14]
Innanzitutto volevo congratularmi per il lavoro. Ad ogni modo, mi chiedevo se fosse possibile aggiungere per ogni comune la relativa mail certificata.

**Comment by matteocontrini** [comment]
Non esiste una fonte unica affidabile con i dati per tutti i comuni, che io sappia. È tecnicamente fattibile fare scraping "intelligente" dei siti web di tutti i comuni, ma è un lavoro un po' mastodontico.

Se può essere utile, il sito "Indice PA" (che non avevo nemmeno idea esistesse fino a ieri) pubblica degli open data in cui ci sono gli indirizzi PEC per molti comuni e in generale amministrazioni pubbliche: https://www.indicepa.gov.it/documentale/n-opendata.php
