### ISSUE TITLE
Question/request: sigla codice fiscale

### ISSUE THREAD

**Issue by G4Zz0L1** [matteocontrini/comuni-json#15]
Non ho avuto modo di guardare le fonti dei dati per vedere se sono inclusi, ma lo chiedo uguale: ci sarebbe modo di aggiungere un campo con la sigla che serve per generare il codice fiscale?

Molte delle tabelle/fonti che ho incontrato finora mancano di quel parametro, a parte qualcuna, ma comunque non hanno aggiornamenti frequenti. Fatemi sapere cosa ne pensate, e se è una richiesta valida.

**Comment by matteocontrini** [comment]
Ciao, da quel che ricordo nel codice fiscale c'è il codice catastale del comune, che c'è già nei dati di questa repository. L'unico problema è che il codice fiscale viene creato alla nascita, quindi non si può usare un database di oggi per calcolare codici fiscali di persone nate nel secolo scorso, ad esempio.

**Comment by G4Zz0L1** [comment]
A quanto pare hai ragione. Nello specifico: il codice usato per il nuovo codice catastale (codice Belfiore) è lo stesso metodo usato per il calcolo del codice fiscale.

https://it.wikipedia.org/wiki/Codice_fiscale#Generazione_del_codice_fiscale

Si può tranquillamente chiudere allora.
