### ISSUE TITLE
Info su sorgente dati

### ISSUE THREAD

**Issue by gionn** [matteocontrini/comuni-json#2]
Ciao,

potresti inserire qualche riferimento nel README di come hai generato il JSON, così da avere un qualcosa che certifichi l'autorevolezza di questi dati, a parte la tua parola?

**Comment by matteocontrini** [comment]
Fatto!
Aggiungo qua che non posso purtroppo garantire l'accuratezza dei dati al 100%, per il fatto che il database CAP è proprietario di Poste Italiane.
