### ISSUE TITLE
Comune di calliano

### ISSUE THREAD

**Issue by paraflu** [matteocontrini/comuni-json#24]
Nel db manca il comune di Calliano

https://www.tuttitalia.it/trentino-alto-adige/57-calliano/

come ti posso aiutare ad integrare i dati?

**Comment by matteocontrini** [comment]
Ciao, nel database sono presenti entrambi i comuni di Calliano:

TN: https://github.com/matteocontrini/comuni-json/blob/6a59ccf880fc6e8a4f33cfa0fd14ed9a10ef0ff0/data/022035-ZcpOd5.json

AT: https://github.com/matteocontrini/comuni-json/blob/6a59ccf880fc6e8a4f33cfa0fd14ed9a10ef0ff0/data/005014-ZcpOd5.json
