### ISSUE TITLE
Dal 23/02/2019 Negrar (VR) è diventato "Negrar di Valpolicella"

### ISSUE THREAD

**Issue by denver-s** [matteocontrini/comuni-json#28]
Da modificare in comuni.json e in data/023052-Z1eLR8y.json

**Comment by matteocontrini** [comment]
Ciao, grazie per la segnalazione. Ho visto infatti che ISTAT ha scritto qualcosa in proposito sul sito, era in todo :)

Faccio un aggiornamento di tutti i nomi dei comuni al più presto, per scrupolo.

**Comment by matteocontrini** [comment]
A quanto pare i dati ISTAT pubblicati [qua](https://www.istat.it/it/archivio/6789) sono aggiornati al 20 febbraio, che è la versione su cui si basa questa repository. Il cambiamento del 23 febbraio non è incluso.

Attenderei quindi la pubblicazione di dati più aggiornati, mi sembra meglio che modificare a mano il file. Non penso sia urgente, giusto?
