### ISSUE TITLE
Aggiornamenti 2017

### ISSUE THREAD

**Issue by matteocontrini** [matteocontrini/comuni-json#3]
Mancano i [nuovi comuni 2017](http://www.tuttitalia.it/variazioni-amministrative/nuovi-comuni-2017/) istituiti per fusione.
In attesa dei nuovi CAP di Poste Italiane...

**Comment by matteocontrini** [comment]
b69ab9ce2e1d182d51eff0a7b175a16d3754a3ca
f6a6332a804c8212e3a6705e25646b0c73a3623b

**Comment by lucapalomba** [comment]
La province di Sud Sardegna non ha la sigla. 
In questo caso ti affidi a qualche Fonte particolare o ti bastano cose tipo Wikipedia?
https://it.wikipedia.org/wiki/Provincia_del_Sud_Sardegna

**Comment by matteocontrini** [comment]
Grazie, è una novità del 10 luglio. Aggiorno subito

http://www.governo.it/articolo/comunicato-stampa-del-consiglio-dei-ministri-n-38/7776
