### ISSUE TITLE
CAP 20060

### ISSUE THREAD

**Issue by mc123401** [matteocontrini/comuni-json#30]
Buongiorno

Vorrei sapere perche' il CAP 20060 e' attribuito a piu' comuni nel milanese.

Grazie

Alberto

**Comment by matteocontrini** [comment]
Ciao, perché ci sono molti comuni con lo stesso CAP: https://www.nonsolocap.it/cap?k=20060+&b=+Cerca+&c=

**Comment by mc123401** [comment]
Grazie per la cortese e veloce risposta. Ma il mio dubbio e' appunto perche' piu' paesi hanno lo stesso CAP ( tra l'altro anche piuttosto distanti tra loro ) . Ma il CAP non doveva essere univoco per paese ? O mi sbaglio io ?

Grazie

Alberto

**Comment by matteocontrini** [comment]
Purtroppo no, i CAP sono un caos indecifrabile. Un CAP può corrispondere a più comuni, oppure può essere associato a un comune e allo stesso tempo a una frazione di un altro comune. In più all'interno di un comune ci possono essere più CAP che identificano le frazioni.

Poi è Poste Italiane a sapere come utilizzarli (bisogna tenere in mente che lo scopo principale dei CAP è il recapito della posta, anche se poi si usano per molte altre cose, purtroppo, aggiungo).

[Su Wikipedia](https://it.wikipedia.org/wiki/Codice_di_avviamento_postale) c'è un approfondimento se vuoi, non che aiuti a venirne a capo 😅

>Lo stesso CAP può corrispondere a più località, anche tra loro non confinanti, ma per le nuove province si è adottato il principio dell'attribuzione univoca dei codici alle agenzie di recapito: un'agenzia di recapito può avere più codici, ma allo stesso codice non devono corrispondere più agenzie. 

Questo database è di conseguenza approssimato, perché non considera cose come i CAP di frazione. Come indicato nel readme per avere una lista di CAP affidabili bisogna fare riferimento al database ufficiale di Poste Italiane (a pagamento), che se non sbaglio associa ogni via e numero civico a un CAP specifico.

Per chi si accontenta, invece... :)
