### ISSUE TITLE
Pensato ad una struttura più ad albero?

### ISSUE THREAD

**Issue by APerricone** [matteocontrini/comuni-json#31]
Ciao,
Non sarebbe più logico e forse più fruibile una versione ad albero tipo:
```json
{"Zone":[
 {"codice":"1","nome":"Nord-ovest", "regioni":[
  {"codice":"01","nome":"Piemonte", "provincie":[
   {"codice":"001","nome":"Torino", "sigla":"TO", "comuni":[
    {"codice":"001001", "nome":"Agliè", "codiceCatastale":"A074","cap":["10011"],"popolazione":2644},
     ...]}
    ...]},
  {"codice":"02","nome":"Valle d'Aosta/Vallée d'Aoste", ...},
  ...]},
 {"codice":"2","nome":"Nord-est", ....},
 ...]
}
```
PS. grazie infinite per lo sforzo, queste informazioni in formato elettronico dovrebbe fornirle direttamente lo stato...

**Comment by mindcreations** [comment]
> PS. grazie infinite per lo sforzo, queste informazioni in formato elettronico dovrebbe fornirle direttamente lo stato...
<Modalità polemica>
Non quando può guadagnarci qualcuno (Poste Italiane), il DB dei CAP è a pagamento e da ciò che ho compreso è solo un file MDB (Microsoft Access) da scaricare! In quel caso avresti anche la precisione del CAP a livello di civico.

Anche Poste potrebbe fare un'API pubblica in cui si possono ottenere questi dati ma perché dovrebbe farlo? In realtà non la fa neanche a pagamento...
</Modalità polemica>

**Comment by APerricone** [comment]
chiuso con e044aad81c679b18c48794f7ba48319a57eb466e
