### ISSUE TITLE
Variazioni CAP comuni provincia Oristano novembre 2017

### ISSUE THREAD

**Issue by inaitana** [matteocontrini/comuni-json#34]
Ciao,

ho notato che non vi risultano le variazioni di CAP per alcuni comuni della provincia di Oristano del 27 novembre 2017. Sono quelli indicati in questo [articolo](https://www.lanuovasardegna.it/oristano/cronaca/2017/11/26/news/poste-italiane-modifica-i-cap-in-9-comuni-1.16170058), che per semplicità vi riassumo:

  Bosa: "09089",
  Flussio: "09090",
  Magomadas: "09090",
  Montresta: "09090",
  Laconi: "09090",
  Modolo: "09090",
  Sagama: "09090",
  Suni: "09090",
  Tinnura: "09090"

Non ho trovato altre fonti più ufficiali di questa (ho visto che a voi risulta un documento delle Poste per la provincia del Sud Sardegna dello stesso periodo), ma a tuttitalia e nonsolocap risultano.

Grazie per il lavoro fantastico!

**Comment by matteocontrini** [comment]
Ho ricontrollato ma non mi risulta che Poste Italiane abbia mai comunicato questi variazioni. Comunque, le ho applicate. Grazie!
