### ISSUE TITLE
verifica dati

### ISSUE THREAD

**Issue by BatClod** [matteocontrini/comuni-json#4]
ciao utilizzando il tuo database mi è capitato di notare che il comune valdaone (registrato gennaio 2015) è inserito con il cap 38080 - il dato corretto sarebbe invece 38091

**Comment by matteocontrini** [comment]
Grazie per la segnalazione. Mi è sfuggito in qualche modo. I dati pubblicati sul sito ANCI non sono aggiornati nemmeno al 2015 evidentemente. Dovrò trovare altre fonti più affidabili per fare una verifica complessiva...

**Comment by matteocontrini** [comment]
Aggiornato :)

https://github.com/matteocontrini/comuni-json/commit/f6a6332a804c8212e3a6705e25646b0c73a3623b
