### ISSUE TITLE
manca cap 52040

### ISSUE THREAD

**Issue by m47730** [matteocontrini/comuni-json#6]
Ciao,
ti dò del tu perchè sento una sorta di vicinanza nei nostri nomi (mi chiamo Matteo Contri) :-)

Ti segnalo che manca il cap 52040, del quale posso darti informazioni soltanto parziali; sicuramente riguarda la provincia di Arezzo (52100) e ~~so per certo che viene~~ dovrebbe essere utilizzato per la località Bagnoro.
Cercando su internet appare anche per vari comuni limitrofi, tipo: Cortona, Monte San Savino (anche se hanno il loro specifico perciò non ho capito se racchiude un'intera zona o meno).

Non so sei hai fonti attendibili su cui cercare.

Grazie per l'ottimo lavoro

**Comment by matteocontrini** [comment]
Ciao Matteo, è un CAP "fantasma". Se fai una [ricerca sul sito](https://www.poste.it/cerca/index.html#/risultati-cerca-cap/52040) delle Poste per 52040 viene fuori "1 risultato" ma in realtà il risultato è 52100 comune di Arezzo.
Il problema è che di solito i CAP vengono assegnati per comune, non per frazione. E quindi a questo punto non so cosa dirti. Non trovo conferma su [NonSoloCAP](http://www.nonsolocap.it/cap?k=52040&b=+Cerca+&c=), ma su [Pagine Bianche](http://www.paginebianche.it/cap?dv=52040) sì, che però dovrebbe usare lo stesso database ufficiale (a pagamento) che usa Poste. Poi c'è [Comuniverso](http://www.comuniverso.it/index.cfm?Comune_di_Civitella%20in%20Val%20di%20Chiana&comune=051016) dell'ANCI che dice che 52040 è il CAP di "Civitella in Val di Chiana".

C'è qualcosa che non torna, direi? Proverei a chiedere direttamente a Poste Italiane se non sapessi per certo che non capirebbero nemmeno la domanda.

**Comment by m47730** [comment]
Conosco una persona dotata di acume che lavorava alle poste (credo sia andata in pensione un paio di anni fa), magari chiedo lumi a lui e ti riferisco.
Potrebbe essere un cap che racchiudeva una serie di comuni che poi sono stati ulteriormente suddivisi con cap univoci, mentre i loro abitanti continuano ad utilizzare il codice generico.
Anche perchè Civitella, Castiglion Fiorentino, Cortona, Foiano della Chiana, Lucignano, Marciano della Chiana, Monte San Savino sono tutti comuni vicini (e tutti con 5204x)

Per adesso chiudo la segnalazione, e la riaprirò quando avrò più informazioni.
Per 'sto benedetto 52040 lo aggiungerò a mano di volta in volta che qualcuno si lamenta.
