### ISSUE TITLE
Formato JSON per campo CAP

### ISSUE THREAD

**Issue by andrea-capigiri** [matteocontrini/comuni-json#7]
Per una corretta formattazione del documento Comuni.json il campo CAP dovrebbe essere rappresentato in qualsiasi caso come array di stringhe

**Comment by primax79** [comment]
concordo
i json dovrebbero essere coerenti per tutti gli elementi

**Comment by matteocontrini** [comment]
D'accordo anche io, l'idea era non introdurre "breaking changes" nel caso qualcuno aggiornasse per via automatica i dati usando il file json. 
Ma si fa presto (?) a modificare la struttura se quello appena spiegato non è un problema così rilevante.

**Comment by m47730** [comment]
Io sono uno di quelli che ha implementato la procedura automatica.
Ho dovuto mettere qualche "if" per le situazioni in cui il file json non era coerente, se facessi la modifica semplicemente non dovrei cambiare nulla perchè le condizioni sarebbero sempre vere (o sempre false non ricordo).
Per me è semaforo verde e mi immagino altri abbiano dovuto gestire le incoerenze in qualche modo
