### ISSUE TITLE
Aggiornamento 2018 (gennaio ok, febbraio ok, marzo ok)

### ISSUE THREAD

**Issue by matteocontrini** [matteocontrini/comuni-json#9]
A seguito dei nuovi comuni istituiti il 1° gennaio, bisogna fare un aggiornamento generale dei dati ISTAT.

**Comment by aletundo** [comment]
Ciao @matteocontrini!

Ti serve una mano per aggiornare? Nella repo non c'è nulla riguardo il processo di estrazione dai CSV dell'ISTAT ed eventuale integrazione con altre fonti altrimenti avrei già provato a farti una pull.

**Comment by matteocontrini** [comment]
Gli script di importazione/aggiornamento li ho in locale perché sono piuttosto rudimentali. Vedo se riesco ad aggiornare almeno i dati istat oggi o domani!

Per i CAP bisogna vedere se Poste li ha decisi, poi guardo anche questo.

**Comment by matteocontrini** [comment]
Scusate, riprogrammo a domani molto probabilmente. Periodo di esami... :)

**Comment by matteocontrini** [comment]
Ho aggiornato i dati. Mancano da aggiornare alcuni CAP della Sardegna comunicati da Poste qualche mese fa (creo un altro issue per questo). Intanto ricordo che i comuni istituiti **dopo** il 1° gennaio 2017 (incluse le fusioni del 2018) hanno CAP provvisorio perché Poste Italiane non ha pubblicato gli aggiornamenti dei CAP.

**Comment by matteocontrini** [comment]
La situazione è complicata quest'anno, ci sono state fusioni ieri e ne arriveranno altre durante l'anno. Riapro l'issue

**Comment by matteocontrini** [comment]
Aggiornati i dati al 1° febbraio 2018.

**Comment by matteocontrini** [comment]
Aggiornati i dati ISTAT al 17 febbraio 2018

**Comment by matteocontrini** [comment]
Aggiornati i CAP in base a quanto comunicato da Poste l'8 marzo 2018. Due note:

- questi nuovi CAP entreranno in vigore dal prossimo 18 giugno
- i nuovi CAP riguardano i comuni istituiti il 1° gennaio 2018, ma non quelli istituiti a febbraio o a marzo

https://github.com/matteocontrini/comuni-json/releases/tag/2018-03-08

![image](https://user-images.githubusercontent.com/2164763/38162292-cc3935ae-34de-11e8-8134-63f616216b0b.png)

**Comment by matteocontrini** [comment]
Aggiornati i dati in seguito alla fusione del 31 marzo 2018. Il CAP del nuovo comune è temporaneamente multiplo e include i due CAP dei comuni soppressi.

https://github.com/matteocontrini/comuni-json/releases/tag/2018-03-31

Le prossime fusioni sono attese nel 2019, quindi chiudo :)
